<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="[Your Name]">

<title>NBA Salary and Performance Analysis: Investigating the Relationship Between Pay and Performance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Final Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final Project_files/libs/quarto-html/quarto.js"></script>
<script src="Final Project_files/libs/quarto-html/popper.min.js"></script>
<script src="Final Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final Project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final Project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">NBA Salary and Performance Analysis: Investigating the Relationship Between Pay and Performance</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>[Your Name] </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This analysis explores the relationship between NBA player salaries and their on-court performance. The sports industry presents a unique opportunity to study labor economics as performance metrics are abundant and salaries are publicly available. We aim to determine which performance metrics most strongly predict player compensation and whether NBA teams efficiently allocate their salary resources.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.95 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'gridExtra'

The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'scales'

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Set default theme for consistent visualizations</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="research-question-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="research-question-hypotheses">1. Research Question &amp; Hypotheses</h2>
<p><strong>Primary Research Question:</strong><br>
To what extent do RAPM (Regularized Adjusted Plus-Minus) and other advanced performance metrics predict NBA player salaries, and are there systematic inefficiencies in how teams compensate players?</p>
<p><strong>Hypotheses:</strong></p>
<ol type="1">
<li><p><strong>H1:</strong> RAPM metrics will have stronger correlation with salary than traditional statistics.</p></li>
<li><p><strong>H2:</strong> Veteran players receive salaries higher than predicted by their performance metrics, suggesting compensation for past performance or reputation.</p></li>
<li><p><strong>H3:</strong> There are systematic inefficiencies in salary allocation across different performance dimensions (offensive vs.&nbsp;defensive RAPM).</p></li>
<li><p><strong>H4:</strong> Salary trends across seasons show a consistent relationship with player performance metrics.</p></li>
</ol>
</section>
<section id="data-acquisition-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-acquisition-preparation">2. Data Acquisition &amp; Preparation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load salary and performance data with the correct column names</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>salaries_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"ranked salary.csv"</span>) <span class="co"># Adjust filename as needed</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>stats_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"rapm.csv"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View structure of datasets</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(salaries_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   578 obs. of  8 variables:
 $ Player          : chr  "Stephen Curry" "Chris Paul" "Russell Westbrook" "James Harden" ...
 $ Salary_Rank_2020: num  1 2 3 4 5 6 7 8 9 10 ...
 $ X2015           : num  11370786 21468695 16744218 15719062 14728844 ...
 $ X2016           : num  12112359 22868827 26540100 26540100 15756438 ...
 $ X2017           : num  34682550 24268959 28299399 28299399 18063850 ...
 $ X2018           : num  37457154 35654150 35665000 30570000 19169800 ...
 $ X2019           : num  40231758 38506482 38506482 38199000 38199000 ...
 $ X2020           : num  43006362 41358814 41358814 41254920 41254920 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(stats_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   6918 obs. of  46 variables:
 $ playerId          : int  101106 101106 101106 101106 101106 101106 101106 101106 101106 101106 ...
 $ playerName        : chr  "Andrew Bogut" "Andrew Bogut" "Andrew Bogut" "Andrew Bogut" ...
 $ LA_RAPM           : num  2.77 1.35 0.31 0.22 -0.11 2.18 0.79 0.63 -0.82 -0.04 ...
 $ LA_RAPM_Rank      : int  22 105 177 180 236 14 87 89 476 256 ...
 $ LA_RAPM__Def      : num  2.99 2.38 1.44 1.04 1.83 2.21 1.06 1.73 0.11 0.06 ...
 $ LA_RAPM__Def_Rank : int  1 21 42 53 62 2 18 4 200 209 ...
 $ LA_RAPM__Off      : num  -0.21 -1.03 -1.13 -0.82 -1.93 -0.03 -0.27 -1.1 -0.93 -0.11 ...
 $ LA_RAPM__Off_Rank : int  248 334 406 370 429 237 328 465 518 316 ...
 $ LA_RAPM__intercept: num  107 106 105 106 105 ...
 $ RAPM              : num  3.06 2.01 0.87 -0.4 0.95 2.64 0.71 -0.19 -0.32 -0.1 ...
 $ RAPM_Rank         : int  18 51 132 275 91 15 112 270 353 280 ...
 $ RAPM__Def         : num  2.57 2.77 2.11 0.29 1.15 1.88 1.25 1.47 0.43 -0.15 ...
 $ RAPM__Def_Rank    : int  3 6 25 177 34 8 21 16 121 324 ...
 $ RAPM__Off         : num  0.49 -0.76 -1.24 -0.69 -0.2 0.76 -0.54 -1.67 -0.75 0.05 ...
 $ RAPM__Off_Rank    : int  131 330 404 337 295 78 373 480 468 228 ...
 $ RAPM__intercept   : num  108 107 104 106 107 ...
 $ RA_EFG            : num  2.99 2.92 1.23 0.46 1.21 2 0.99 -0.31 0.01 -0.05 ...
 $ RA_EFG_Rank       : num  8 12 82 159 38 4 24 347 233 291 ...
 $ RA_EFG__Def       : num  1.92 2.24 1.54 1.2 0.44 1.1 0.72 0.53 0.27 -0.1 ...
 $ RA_EFG__Def_Rank  : int  9 4 29 44 97 1 16 35 114 343 ...
 $ RA_EFG__Off       : num  1.07 0.68 -0.31 -0.74 0.77 0.9 0.27 -0.83 -0.26 0.05 ...
 $ RA_EFG__Off_Rank  : int  50 99 299 375 42 19 102 479 416 198 ...
 $ RA_EFG__intercept : num  51.4 51.3 49.9 50.9 53.5 ...
 $ RA_FTR            : num  -0.19 2.61 -0.29 0.39 -0.58 -0.9 -1.11 -0.21 -0.5 -0.09 ...
 $ RA_FTR_Rank       : int  241 40 261 177 356 457 461 313 451 301 ...
 $ RA_FTR__Def       : num  0.94 2.42 1.12 0.82 0.5 0.5 0.8 0.27 0.05 0.06 ...
 $ RA_FTR__Def_Rank  : int  107 27 103 130 109 77 26 116 225 204 ...
 $ RA_FTR__Off       : num  -1.13 0.19 -1.42 -0.43 -1.08 -1.4 -1.92 -0.48 -0.55 -0.16 ...
 $ RA_FTR__Off_Rank  : int  353 179 406 299 439 492 476 416 495 346 ...
 $ RA_FTR__intercept : num  36.7 36 33.4 33 14.6 ...
 $ RA_ORBD           : num  2.36 1.28 0.1 -0.34 0.83 0.11 -0.24 0 0.64 -0.34 ...
 $ RA_ORBD_Rank      : num  11 50 205 292 65 213 302 247 94 363 ...
 $ RA_ORBD__Def      : num  2.04 0.87 0.98 0.09 0.82 0.95 0.6 0.64 0.32 0.16 ...
 $ RA_ORBD__Def_Rank : num  1 43 41 212 28 28 61 44 122 194 ...
 $ RA_ORBD__Off      : num  0.32 0.41 -0.88 -0.42 0.01 -0.84 -0.85 -0.63 0.32 -0.5 ...
 $ RA_ORBD__Off_Rank : num  132 121 409 330 238 449 432 412 139 429 ...
 $ RA_ORBD__intercept: num  23.4 23 23.3 23.3 18.9 ...
 $ RA_TOV            : num  -0.78 -1.49 0.03 -0.71 -1.94 -0.37 -0.68 0.12 -0.39 -0.01 ...
 $ RA_TOV_Rank       : int  384 440 222 391 481 391 446 168 450 274 ...
 $ RA_TOV__Def       : num  -0.42 -0.84 0.35 -0.84 -0.48 0.03 -0.28 0.43 0.01 -0.09 ...
 $ RA_TOV__Def_Rank  : int  357 431 118 445 428 215 393 48 251 328 ...
 $ RA_TOV__Off       : num  -0.36 -0.65 -0.32 0.13 -1.46 -0.39 -0.4 -0.31 -0.4 0.08 ...
 $ RA_TOV__Off_Rank  : int  342 405 345 189 482 435 436 413 495 190 ...
 $ RA_TOV__intercept : num  -15.2 -15.7 -15.9 -15.5 -15.4 ...
 $ season            : chr  "2009-10" "2010-11" "2011-12" "2012-13" ...
 $ primaryKey        : chr  "101106_2009-10" "101106_2010-11" "101106_2011-12" "101106_2012-13" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display first few rows of each dataset</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(salaries_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Player Salary_Rank_2020    X2015    X2016    X2017    X2018
1     Stephen Curry                1 11370786 12112359 34682550 37457154
2        Chris Paul                2 21468695 22868827 24268959 35654150
3 Russell Westbrook                3 16744218 26540100 28299399 35665000
4      James Harden                4 15719062 26540100 28299399 30570000
5         John Wall                5 14728844 15756438 18063850 19169800
6      Kevin Durant                6 21971850 26540100 25000000 30000000
     X2019    X2020
1 40231758 43006362
2 38506482 41358814
3 38506482 41358814
4 38199000 41254920
5 38199000 41254920
6 37199000 40108950</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stats_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  playerId   playerName LA_RAPM LA_RAPM_Rank LA_RAPM__Def LA_RAPM__Def_Rank
1   101106 Andrew Bogut    2.77           22         2.99                 1
2   101106 Andrew Bogut    1.35          105         2.38                21
3   101106 Andrew Bogut    0.31          177         1.44                42
4   101106 Andrew Bogut    0.22          180         1.04                53
5   101106 Andrew Bogut   -0.11          236         1.83                62
6   101106 Andrew Bogut    2.18           14         2.21                 2
  LA_RAPM__Off LA_RAPM__Off_Rank LA_RAPM__intercept  RAPM RAPM_Rank RAPM__Def
1        -0.21               248             107.38  3.06        18      2.57
2        -1.03               334             106.00  2.01        51      2.77
3        -1.13               406             104.52  0.87       132      2.11
4        -0.82               370             105.78 -0.40       275      0.29
5        -1.93               429             105.21  0.95        91      1.15
6        -0.03               237             106.15  2.64        15      1.88
  RAPM__Def_Rank RAPM__Off RAPM__Off_Rank RAPM__intercept RA_EFG RA_EFG_Rank
1              3      0.49            131          107.67   2.99           8
2              6     -0.76            330          107.22   2.92          12
3             25     -1.24            404          104.28   1.23          82
4            177     -0.69            337          106.10   0.46         159
5             34     -0.20            295          107.02   1.21          38
6              8      0.76             78          106.06   2.00           4
  RA_EFG__Def RA_EFG__Def_Rank RA_EFG__Off RA_EFG__Off_Rank RA_EFG__intercept
1        1.92                9        1.07               50             51.43
2        2.24                4        0.68               99             51.26
3        1.54               29       -0.31              299             49.91
4        1.20               44       -0.74              375             50.94
5        0.44               97        0.77               42             53.48
6        1.10                1        0.90               19             52.94
  RA_FTR RA_FTR_Rank RA_FTR__Def RA_FTR__Def_Rank RA_FTR__Off RA_FTR__Off_Rank
1  -0.19         241        0.94              107       -1.13              353
2   2.61          40        2.42               27        0.19              179
3  -0.29         261        1.12              103       -1.42              406
4   0.39         177        0.82              130       -0.43              299
5  -0.58         356        0.50              109       -1.08              439
6  -0.90         457        0.50               77       -1.40              492
  RA_FTR__intercept RA_ORBD RA_ORBD_Rank RA_ORBD__Def RA_ORBD__Def_Rank
1             36.74    2.36           11         2.04                 1
2             36.02    1.28           50         0.87                43
3             33.40    0.10          205         0.98                41
4             32.95   -0.34          292         0.09               212
5             14.64    0.83           65         0.82                28
6             14.42    0.11          213         0.95                28
  RA_ORBD__Off RA_ORBD__Off_Rank RA_ORBD__intercept RA_TOV RA_TOV_Rank
1         0.32               132              23.36  -0.78         384
2         0.41               121              23.04  -1.49         440
3        -0.88               409              23.32   0.03         222
4        -0.42               330              23.26  -0.71         391
5         0.01               238              18.92  -1.94         481
6        -0.84               449              18.41  -0.37         391
  RA_TOV__Def RA_TOV__Def_Rank RA_TOV__Off RA_TOV__Off_Rank RA_TOV__intercept
1       -0.42              357       -0.36              342            -15.18
2       -0.84              431       -0.65              405            -15.69
3        0.35              118       -0.32              345            -15.86
4       -0.84              445        0.13              189            -15.52
5       -0.48              428       -1.46              482            -15.40
6        0.03              215       -0.39              435            -14.97
   season     primaryKey
1 2009-10 101106_2009-10
2 2010-11 101106_2010-11
3 2011-12 101106_2011-12
4 2012-13 101106_2012-13
5 2013-14 101106_2013-14
6 2014-15 101106_2014-15</code></pre>
</div>
</div>
<section id="data-source-description" class="level3">
<h3 class="anchored" data-anchor-id="data-source-description">Data Source Description</h3>
<p>Our analysis combines two primary datasets:</p>
<ol type="1">
<li><p><strong>NBA Player Salaries</strong> (<code>ranked_salary.csv</code>): Contains player names and their annual salaries across multiple seasons (2015-2020).</p></li>
<li><p><strong>Player Performance Statistics</strong> (<code>rapm.csv</code>): Contains comprehensive player statistics including RAPM metrics for offensive and defensive performance.</p></li>
</ol>
<p>These datasets provide the necessary variables to study the relationship between player compensation and on-court contribution.</p>
</section>
</section>
<section id="data-cleaning-transformation" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning-transformation">3. Data Cleaning &amp; Transformation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean salaries data - adjust column names based on actual data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>salaries_clean <span class="ot">&lt;-</span> salaries_df <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Rename columns for clarity if needed</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Player =</span> Player) <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Select relevant salary columns</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Player, X2020, X2019, X2018, X2017, X2016, X2015) <span class="sc">%&gt;%</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convert to long format for multi-year analysis</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"X"</span>),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"Year"</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"Salary"</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Clean up year format</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">Year =</span> <span class="fu">as.numeric</span>(<span class="fu">str_replace</span>(Year, <span class="st">"X"</span>, <span class="st">""</span>)),</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Remove any rows with NA salaries</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Salary =</span> <span class="fu">as.numeric</span>(Salary)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Salary))</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean stats data - adjust based on actual columns</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>stats_clean <span class="ot">&lt;-</span> stats_df <span class="sc">%&gt;%</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Rename the player column to match salaries dataset</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Player =</span> playerName) <span class="sc">%&gt;%</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create a year variable if there's a season column</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">Year =</span> <span class="fu">as.numeric</span>(<span class="fu">sub</span>(<span class="st">"^(</span><span class="sc">\\</span><span class="st">d{4}).*"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, season)),</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create derived metrics if needed</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">Offensive_Value =</span> LA_RAPM__Off,</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">Defensive_Value =</span> LA_RAPM__Def,</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_Value =</span> LA_RAPM</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge datasets - make sure the joining columns match</span></span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>player_data <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(stats_clean, salaries_clean, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Player"</span>, <span class="st">"Year"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove any invalid data</span></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Salary), <span class="sc">!</span><span class="fu">is.na</span>(LA_RAPM))</span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values</span></span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a>missing_data <span class="ot">&lt;-</span> player_data <span class="sc">%&gt;%</span></span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.)))) <span class="sc">%&gt;%</span></span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(Variable, Missing_Count) <span class="sc">%&gt;%</span></span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Missing_Count <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Missing_Count))</span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Display missing data</span></span>
<span id="cb20-47"><a href="#cb20-47" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">nrow</span>(missing_data) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb20-48"><a href="#cb20-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"Variables with missing values:"</span>)</span>
<span id="cb20-49"><a href="#cb20-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(missing_data)</span>
<span id="cb20-50"><a href="#cb20-50" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb20-51"><a href="#cb20-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"No missing values found in the merged dataset"</span>)</span>
<span id="cb20-52"><a href="#cb20-52" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "No missing values found in the merged dataset"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of merged data</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Merged dataset has"</span>, <span class="fu">nrow</span>(player_data), <span class="st">"player-season observations</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Merged dataset has 1922 player-season observations</code></pre>
</div>
</div>
<section id="data-cleaning-process" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-process">Data Cleaning Process:</h3>
<ol type="1">
<li>Standardized player names between datasets</li>
<li>Transformed salary data from wide to long format to enable multi-year analysis</li>
<li>Created derived performance metrics from raw RAPM data</li>
<li>Combined datasets using player names and years as the joining keys</li>
</ol>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-eda">4. Exploratory Data Analysis (EDA)</h2>
<section id="summary-statistics" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics">4.1 Summary Statistics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Key statistics summary</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>performance_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"LA_RAPM"</span>, <span class="st">"LA_RAPM__Off"</span>, <span class="st">"LA_RAPM__Def"</span>, <span class="st">"RAPM"</span>, <span class="st">"Salary"</span>, <span class="st">"Year"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> player_data <span class="sc">%&gt;%</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(performance_vars)) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a more readable summary table</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> player_data <span class="sc">%&gt;%</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(performance_vars)) <span class="sc">%&gt;%</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="at">Mean =</span> <span class="sc">~</span><span class="fu">mean</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>                        <span class="at">Median =</span> <span class="sc">~</span><span class="fu">median</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>                        <span class="at">SD =</span> <span class="sc">~</span><span class="fu">sd</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>                        <span class="at">Min =</span> <span class="sc">~</span><span class="fu">min</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>                        <span class="at">Max =</span> <span class="sc">~</span><span class="fu">max</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(), </span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="fu">c</span>(<span class="st">"Variable"</span>, <span class="st">"Statistic"</span>),</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_pattern =</span> <span class="st">"(.*)_(.*)"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Statistic, <span class="at">values_from =</span> value) <span class="sc">%&gt;%</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">factor</span>(Variable, <span class="at">levels =</span> performance_vars))</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Display summary statistics</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(summary_table, <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">caption =</span> <span class="st">"Summary Statistics of Key Variables"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary Statistics of Key Variables</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LA_RAPM</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-3.19</td>
<td style="text-align: right;">4.90</td>
</tr>
<tr class="even">
<td style="text-align: left;">LA_RAPM__Off</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">-2.73</td>
<td style="text-align: right;">3.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LA_RAPM__Def</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">-2.26</td>
<td style="text-align: right;">3.19</td>
</tr>
<tr class="even">
<td style="text-align: left;">RAPM</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">-3.99</td>
<td style="text-align: right;">5.73</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Salary</td>
<td style="text-align: right;">7645168.46</td>
<td style="text-align: right;">3691239.50</td>
<td style="text-align: right;">8553260.42</td>
<td style="text-align: right;">24611.00</td>
<td style="text-align: right;">43006362.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Year</td>
<td style="text-align: right;">2018.01</td>
<td style="text-align: right;">2018.00</td>
<td style="text-align: right;">1.66</td>
<td style="text-align: right;">2015.00</td>
<td style="text-align: right;">2020.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="salary-distribution" class="level3">
<h3 class="anchored" data-anchor-id="salary-distribution">4.2 Salary Distribution</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Salary distribution visualizations</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> Salary)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>(<span class="at">scale =</span> <span class="dv">1</span><span class="sc">/</span><span class="fl">1e6</span>, <span class="at">suffix =</span> <span class="st">"M"</span>)) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of NBA Player Salaries"</span>, </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Highly right-skewed distribution suggests log transformation needed"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Salary ($M)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log</span>(Salary))) <span class="sc">+</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Log-Transformed Salary Distribution"</span>, </span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"More normally distributed after log transformation"</span>,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Log(Salary)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="co"># QQ plot for log salary</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">log</span>(Salary))) <span class="sc">+</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span> </span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Q-Q Plot of Log-Transformed Salary"</span>,</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Testing for normality of log salaries"</span>,</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Theoretical Quantiles"</span>, </span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Sample Quantiles"</span>) <span class="sc">+</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Salary by year boxplot</span></span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Year), <span class="at">y =</span> Salary<span class="sc">/</span><span class="fl">1e6</span>, <span class="at">fill =</span> <span class="fu">factor</span>(Year))) <span class="sc">+</span></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>(<span class="at">suffix =</span> <span class="st">"M"</span>)) <span class="sc">+</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Salary Distribution by Year"</span>,</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Salary ($M)"</span>) <span class="sc">+</span></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plots</span></span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, p3, p4, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Observations:</strong> - NBA salaries show a strong positive skew with a few players earning significantly more than others - Log transformation produces a more normally distributed variable (confirmed by Q-Q plot), which will be better for regression analysis - The year-by-year salary distribution shows an increasing trend, likely reflecting salary cap growth</p>
</section>
<section id="performance-metrics-distribution" class="level3">
<h3 class="anchored" data-anchor-id="performance-metrics-distribution">4.3 Performance Metrics Distribution</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plots for key performance metrics</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> LA_RAPM)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">25</span>, <span class="at">fill =</span> <span class="st">"darkgreen"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of LA_RAPM"</span>, <span class="at">x =</span> <span class="st">"LA_RAPM"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>p6 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> LA_RAPM__Off)) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">25</span>, <span class="at">fill =</span> <span class="st">"darkred"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Offensive RAPM"</span>, <span class="at">x =</span> <span class="st">"LA_RAPM__Off"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>p7 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> LA_RAPM__Def)) <span class="sc">+</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">25</span>, <span class="at">fill =</span> <span class="st">"darkorange"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Defensive RAPM"</span>, <span class="at">x =</span> <span class="st">"LA_RAPM__Def"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>p8 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> RAPM)) <span class="sc">+</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">25</span>, <span class="at">fill =</span> <span class="st">"darkblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of RAPM"</span>, <span class="at">x =</span> <span class="st">"RAPM"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plots</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p5, p6, p7, p8, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Observations:</strong> - RAPM metrics are approximately normally distributed around zero - The distributions of offensive and defensive RAPM show similar patterns - These distributions differ from typical salary distributions, suggesting a non-linear relationship between performance and compensation</p>
</section>
<section id="salary-vs.-performance-relationships" class="level3">
<h3 class="anchored" data-anchor-id="salary-vs.-performance-relationships">4.4 Salary vs.&nbsp;Performance Relationships</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Performance plot function </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>performance_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(data, metric, title, <span class="at">log_y =</span> <span class="cn">FALSE</span>) {</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes_string</span>(<span class="at">x =</span> metric, <span class="at">y =</span> <span class="st">"Salary"</span>)) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">factor</span>(Year)), <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>(<span class="at">scale =</span> <span class="dv">1</span><span class="sc">/</span><span class="fl">1e6</span>, <span class="at">suffix =</span> <span class="st">"M"</span>)) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title, </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Salary ($M)"</span>, </span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> metric,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"Year"</span>) <span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(log_y) {</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>(<span class="at">scale =</span> <span class="dv">1</span><span class="sc">/</span><span class="fl">1e6</span>, <span class="at">suffix =</span> <span class="st">"M"</span>)) <span class="sc">+</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>         <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Salary ($M, log scale)"</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(p)</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plots with log-transformed salary</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>p9 <span class="ot">&lt;-</span> <span class="fu">performance_plot</span>(player_data, <span class="st">"LA_RAPM"</span>, <span class="st">"Salary vs LA_RAPM"</span>, <span class="at">log_y =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Scale for y is already present.
Adding another scale for y, which will replace the existing scale.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>p10 <span class="ot">&lt;-</span> <span class="fu">performance_plot</span>(player_data, <span class="st">"LA_RAPM__Off"</span>, <span class="st">"Salary vs Offensive RAPM"</span>, <span class="at">log_y =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Scale for y is already present.
Adding another scale for y, which will replace the existing scale.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>p11 <span class="ot">&lt;-</span> <span class="fu">performance_plot</span>(player_data, <span class="st">"LA_RAPM__Def"</span>, <span class="st">"Salary vs Defensive RAPM"</span>, <span class="at">log_y =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Scale for y is already present.
Adding another scale for y, which will replace the existing scale.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>p12 <span class="ot">&lt;-</span> <span class="fu">performance_plot</span>(player_data, <span class="st">"RAPM"</span>, <span class="st">"Salary vs RAPM"</span>, <span class="at">log_y =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Scale for y is already present.
Adding another scale for y, which will replace the existing scale.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plots</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p9, p10, p11, p12, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Observations:</strong> - Clear positive relationships between salary and each RAPM metric - The LOESS smoothing curves suggest non-linear relationships - The relationship appears stronger for offensive metrics than defensive metrics - Year-to-year variation is evident in the salary-performance relationship</p>
</section>
<section id="year-over-year-trends" class="level3">
<h3 class="anchored" data-anchor-id="year-over-year-trends">4.5 Year-over-Year Trends</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Year-over-year visualization</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>year_summary <span class="ot">&lt;-</span> player_data <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Avg_Salary =</span> <span class="fu">mean</span>(Salary, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median_Salary =</span> <span class="fu">median</span>(Salary, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Avg_RAPM =</span> <span class="fu">mean</span>(LA_RAPM, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Correlation =</span> <span class="fu">cor</span>(Salary, LA_RAPM, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plots</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>p13 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(year_summary, <span class="fu">aes</span>(<span class="at">x =</span> Year)) <span class="sc">+</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Avg_Salary<span class="sc">/</span><span class="fl">1e6</span>), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> Avg_Salary<span class="sc">/</span><span class="fl">1e6</span>), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">label_dollar</span>(<span class="at">suffix =</span> <span class="st">"M"</span>)) <span class="sc">+</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average NBA Salary by Year"</span>, </span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Salary ($M)"</span>, </span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>) <span class="sc">+</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>p14 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(year_summary, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Correlation)) <span class="sc">+</span></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"darkred"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"darkred"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Salary-RAPM Correlation by Year"</span>,</span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Correlation Coefficient"</span>,</span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>) <span class="sc">+</span></span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Salary vs RAPM by year</span></span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a>p15 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> LA_RAPM, <span class="at">y =</span> <span class="fu">log</span>(Salary))) <span class="sc">+</span></span>
<span id="cb39-31"><a href="#cb39-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb39-32"><a href="#cb39-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb39-33"><a href="#cb39-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Year) <span class="sc">+</span></span>
<span id="cb39-34"><a href="#cb39-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Salary vs RAPM Relationship by Year"</span>,</span>
<span id="cb39-35"><a href="#cb39-35" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"LA_RAPM"</span>,</span>
<span id="cb39-36"><a href="#cb39-36" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Log Salary"</span>) <span class="sc">+</span></span>
<span id="cb39-37"><a href="#cb39-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb39-38"><a href="#cb39-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-39"><a href="#cb39-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Show plots</span></span>
<span id="cb39-40"><a href="#cb39-40" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p13, p14, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p15)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Observations:</strong> - Average salaries show a clear upward trend over the years - The correlation between RAPM and salary fluctuates by year - The relationship between performance and salary appears relatively consistent across years, but with some variation in slope</p>
</section>
</section>
<section id="correlation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="correlation-analysis">5. Correlation Analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select variables for correlation analysis</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>player_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"LA_RAPM"</span>, <span class="st">"LA_RAPM__Off"</span>, <span class="st">"LA_RAPM__Def"</span>, <span class="st">"RAPM"</span>, <span class="st">"RAPM__Off"</span>, <span class="st">"RAPM__Def"</span>, <span class="st">"Salary"</span>, <span class="st">"Year"</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>player_corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(player_data[player_vars], <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create enhanced correlation plot</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(player_corr, <span class="at">method =</span> <span class="st">"color"</span>, <span class="at">type =</span> <span class="st">"upper"</span>, </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.col =</span> <span class="st">"black"</span>, <span class="at">tl.srt =</span> <span class="dv">45</span>,</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">addCoef.col =</span> <span class="st">"black"</span>, <span class="at">number.cex =</span> <span class="fl">0.7</span>,</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"#D73027"</span>, <span class="st">"#FFFFBF"</span>, <span class="st">"#1A9850"</span>))(<span class="dv">200</span>),</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Correlation Matrix of Player Variables"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a dataframe of correlations with salary</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>salary_corr <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">names</span>(player_corr[<span class="st">"Salary"</span>, ]),</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Correlation =</span> <span class="fu">as.numeric</span>(player_corr[<span class="st">"Salary"</span>, ])</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Variable <span class="sc">!=</span> <span class="st">"Salary"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Correlation))</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot correlations with salary</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(salary_corr, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Variable, Correlation), <span class="at">y =</span> Correlation)) <span class="sc">+</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Correlations with Player Salary"</span>,</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Which metrics have strongest relationship with compensation?"</span>,</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Correlation Coefficient"</span>) <span class="sc">+</span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Observations:</strong> - LA_RAPM metrics show moderate positive correlations with salary - Offensive metrics generally show stronger correlations with salary than defensive metrics - Year also shows a positive correlation with salary, reflecting the increasing salary cap - There’s high correlation among different RAPM variants, suggesting they measure similar aspects of performance</p>
</section>
<section id="advanced-exploratory-analysis" class="level2">
<h2 class="anchored" data-anchor-id="advanced-exploratory-analysis">6. Advanced Exploratory Analysis</h2>
<section id="offensive-vs.-defensive-value" class="level3">
<h3 class="anchored" data-anchor-id="offensive-vs.-defensive-value">6.1 Offensive vs.&nbsp;Defensive Value</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate offensive vs defensive balance</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>player_data <span class="ot">&lt;-</span> player_data <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Off_Def_Ratio =</span> <span class="fu">ifelse</span>(LA_RAPM__Def <span class="sc">!=</span> <span class="dv">0</span>, LA_RAPM__Off <span class="sc">/</span> <span class="fu">abs</span>(LA_RAPM__Def), <span class="cn">NA</span>),</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Off_Bias =</span> <span class="fu">ifelse</span>(LA_RAPM <span class="sc">!=</span> <span class="dv">0</span>, LA_RAPM__Off <span class="sc">/</span> LA_RAPM, <span class="cn">NA</span>),</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Value_Category =</span> <span class="fu">case_when</span>(</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>      LA_RAPM__Off <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> LA_RAPM__Def <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Two-Way Positive"</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>      LA_RAPM__Off <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> LA_RAPM__Def <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Offense Only"</span>,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>      LA_RAPM__Off <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">&amp;</span> LA_RAPM__Def <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Defense Only"</span>,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>      LA_RAPM__Off <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">&amp;</span> LA_RAPM__Def <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Negative Impact"</span>,</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Unknown"</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize offensive vs defensive RAPM</span></span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> LA_RAPM__Def, <span class="at">y =</span> LA_RAPM__Off)) <span class="sc">+</span></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">log</span>(Salary), <span class="at">size =</span> Salary), <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">name =</span> <span class="st">"Log Salary"</span>) <span class="sc">+</span></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">name =</span> <span class="st">"Salary"</span>, <span class="at">labels =</span> <span class="fu">label_dollar</span>(<span class="at">scale =</span> <span class="dv">1</span><span class="sc">/</span><span class="fl">1e6</span>, <span class="at">suffix =</span> <span class="st">"M"</span>)) <span class="sc">+</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray"</span>) <span class="sc">+</span></span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray"</span>) <span class="sc">+</span></span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Offensive vs Defensive RAPM"</span>,</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"With salary indicated by color and size"</span>,</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Defensive RAPM"</span>,</span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Offensive RAPM"</span>) <span class="sc">+</span></span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Salary by player value category</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> Value_Category, <span class="at">y =</span> <span class="fu">log</span>(Salary), <span class="at">fill =</span> Value_Category)) <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Salary Distribution by Player Value Type"</span>,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Log Salary"</span>) <span class="sc">+</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="year-over-year-performance-vs.-salary-change" class="level3">
<h3 class="anchored" data-anchor-id="year-over-year-performance-vs.-salary-change">6.2 Year-over-Year Performance vs.&nbsp;Salary Change</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a dataset with year-over-year changes for players</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co"># First identify players with multiple years of data</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>player_years <span class="ot">&lt;-</span> player_data <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Player) <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Years =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Years <span class="sc">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create lagged variables for returning players</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>player_changes <span class="ot">&lt;-</span> player_data <span class="sc">%&gt;%</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Player <span class="sc">%in%</span> player_years<span class="sc">$</span>Player) <span class="sc">%&gt;%</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Player, Year) <span class="sc">%&gt;%</span></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Player) <span class="sc">%&gt;%</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Prev_Year =</span> <span class="fu">lag</span>(Year),</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">Prev_RAPM =</span> <span class="fu">lag</span>(LA_RAPM),</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">RAPM_Change =</span> LA_RAPM <span class="sc">-</span> <span class="fu">lag</span>(LA_RAPM),</span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Prev_Salary =</span> <span class="fu">lag</span>(Salary),</span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">Salary_Change =</span> Salary <span class="sc">-</span> <span class="fu">lag</span>(Salary),</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">Salary_Pct_Change =</span> (Salary <span class="sc">-</span> <span class="fu">lag</span>(Salary)) <span class="sc">/</span> <span class="fu">lag</span>(Salary) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Prev_Year)) <span class="co"># Remove first observation for each player</span></span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot year-over-year changes</span></span>
<span id="cb46-24"><a href="#cb46-24" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(player_changes, <span class="fu">aes</span>(<span class="at">x =</span> RAPM_Change, <span class="at">y =</span> Salary_Pct_Change)) <span class="sc">+</span></span>
<span id="cb46-25"><a href="#cb46-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb46-26"><a href="#cb46-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb46-27"><a href="#cb46-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray"</span>) <span class="sc">+</span></span>
<span id="cb46-28"><a href="#cb46-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray"</span>) <span class="sc">+</span></span>
<span id="cb46-29"><a href="#cb46-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Performance Change vs. Salary Change"</span>,</span>
<span id="cb46-30"><a href="#cb46-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Do salary increases follow performance improvements?"</span>,</span>
<span id="cb46-31"><a href="#cb46-31" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Change in RAPM"</span>,</span>
<span id="cb46-32"><a href="#cb46-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"% Change in Salary"</span>) <span class="sc">+</span></span>
<span id="cb46-33"><a href="#cb46-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="regression-models" class="level2">
<h2 class="anchored" data-anchor-id="regression-models">7. Regression Models</h2>
<section id="basic-model-rapm-metrics" class="level3">
<h3 class="anchored" data-anchor-id="basic-model-rapm-metrics">7.1 Basic Model: RAPM Metrics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 1: Simple RAPM model</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Salary) <span class="sc">~</span> LA_RAPM <span class="sc">+</span> Year, <span class="at">data =</span> player_data)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Salary) ~ LA_RAPM + Year, data = player_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8720 -0.7725  0.1017  1.0222  2.7866 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 130.39397   37.35136   3.491 0.000492 ***
LA_RAPM       0.37583    0.03075  12.221  &lt; 2e-16 ***
Year         -0.05715    0.01851  -3.088 0.002046 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.345 on 1919 degrees of freedom
Multiple R-squared:  0.07993,   Adjusted R-squared:  0.07897 
F-statistic: 83.36 on 2 and 1919 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="offensive-vs.-defensive-components" class="level3">
<h3 class="anchored" data-anchor-id="offensive-vs.-defensive-components">7.2 Offensive vs.&nbsp;Defensive Components</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 2: Separate offensive and defensive components</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Salary) <span class="sc">~</span> LA_RAPM__Off <span class="sc">+</span> LA_RAPM__Def <span class="sc">+</span> Year, <span class="at">data =</span> player_data)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Salary) ~ LA_RAPM__Off + LA_RAPM__Def + Year, 
    data = player_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8794 -0.7645  0.0970  1.0227  2.7866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  127.00625   37.25435   3.409 0.000665 ***
LA_RAPM__Off   0.47333    0.04138  11.437  &lt; 2e-16 ***
LA_RAPM__Def   0.23552    0.05040   4.673 3.18e-06 ***
Year          -0.05547    0.01846  -3.005 0.002692 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.341 on 1918 degrees of freedom
Multiple R-squared:  0.0858,    Adjusted R-squared:  0.08437 
F-statistic:    60 on 3 and 1918 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check multicollinearity</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>LA_RAPM__Off LA_RAPM__Def         Year 
    1.014062     1.008428     1.008290 </code></pre>
</div>
</div>
<p>In Model 2, both offensive and defensive performance metrics are significant predictors of NBA player salary. A 1-unit increase in offensive RAPM is associated with a 47.3% increase in salary, while a 1-unit increase in defensive RAPM corresponds to a 23.6% increase, holding other variables constant. Salaries appear to decline slightly over time when controlling for performance, with each additional year associated with a 5.5% decrease. However, the model explains only about 8.6% of the variance in salaries, suggesting that many non-performance factors influence pay. No multicollinearity issues are detected.</p>
</section>
<section id="non-linear-effects" class="level3">
<h3 class="anchored" data-anchor-id="non-linear-effects">7.3 Non-Linear Effects</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 3: Testing for non-linear effects</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Salary) <span class="sc">~</span> LA_RAPM <span class="sc">+</span> <span class="fu">I</span>(LA_RAPM<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> Year, <span class="at">data =</span> player_data)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Salary) ~ LA_RAPM + I(LA_RAPM^2) + Year, data = player_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.7320 -0.7435  0.0456  1.0168  2.5822 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  115.84787   36.82943   3.146  0.00168 ** 
LA_RAPM        0.27127    0.03312   8.191 4.66e-16 ***
I(LA_RAPM^2)   0.13812    0.01771   7.801 1.00e-14 ***
Year          -0.05001    0.01825  -2.740  0.00620 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.324 on 1918 degrees of freedom
Multiple R-squared:  0.1082,    Adjusted R-squared:  0.1068 
F-statistic: 77.59 on 3 and 1918 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this quadratic model, both the linear and squared terms for RAPM are positive and highly significant. This suggests that player salary increases at an increasing rate with RAPM — players with exceptionally high RAPM earn disproportionately more than players with moderate RAPM. The adjusted R² improves to 10.7%, indicating that introducing nonlinearity better captures salary variation than a purely linear model. As in previous models, the year coefficient is negative, suggesting slight salary declines over time when holding performance constant.</p>
</section>
<section id="interaction-with-year" class="level3">
<h3 class="anchored" data-anchor-id="interaction-with-year">7.4 Interaction with Year</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 4: Performance-year interaction</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Salary) <span class="sc">~</span> LA_RAPM <span class="sc">*</span> <span class="fu">factor</span>(Year), <span class="at">data =</span> player_data)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Salary) ~ LA_RAPM * factor(Year), data = player_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8349 -0.7879  0.1009  1.0220  2.8517 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              15.08257    0.09966 151.335  &lt; 2e-16 ***
LA_RAPM                   0.32254    0.08487   3.800 0.000149 ***
factor(Year)2016          0.17022    0.13355   1.275 0.202623    
factor(Year)2017          0.11640    0.12864   0.905 0.365655    
factor(Year)2018          0.11444    0.12488   0.916 0.359576    
factor(Year)2019         -0.17187    0.12020  -1.430 0.152911    
factor(Year)2020         -0.14612    0.11697  -1.249 0.211730    
LA_RAPM:factor(Year)2016  0.03591    0.11663   0.308 0.758170    
LA_RAPM:factor(Year)2017 -0.03390    0.12000  -0.283 0.777578    
LA_RAPM:factor(Year)2018  0.08010    0.11217   0.714 0.475265    
LA_RAPM:factor(Year)2019  0.04112    0.10834   0.380 0.704330    
LA_RAPM:factor(Year)2020  0.14536    0.10849   1.340 0.180438    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.343 on 1910 degrees of freedom
Multiple R-squared:  0.08635,   Adjusted R-squared:  0.08109 
F-statistic: 16.41 on 11 and 1910 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare models</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>models_comparison <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"Basic RAPM"</span>, <span class="st">"Off-Def Components"</span>, <span class="st">"Non-Linear"</span>, <span class="st">"Year Interaction"</span>),</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">R_Squared =</span> <span class="fu">c</span>(<span class="fu">summary</span>(model1)<span class="sc">$</span>r.squared, </span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>                <span class="fu">summary</span>(model2)<span class="sc">$</span>r.squared,</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>                <span class="fu">summary</span>(model3)<span class="sc">$</span>r.squared,</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>                <span class="fu">summary</span>(model4)<span class="sc">$</span>r.squared),</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Adj_R_Squared =</span> <span class="fu">c</span>(<span class="fu">summary</span>(model1)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">summary</span>(model2)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">summary</span>(model3)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">summary</span>(model4)<span class="sc">$</span>adj.r.squared)</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model comparison table</span></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(models_comparison, <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Regression Model Comparison"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Regression Model Comparison</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">R_Squared</th>
<th style="text-align: right;">Adj_R_Squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Basic RAPM</td>
<td style="text-align: right;">0.0799</td>
<td style="text-align: right;">0.0790</td>
</tr>
<tr class="even">
<td style="text-align: left;">Off-Def Components</td>
<td style="text-align: right;">0.0858</td>
<td style="text-align: right;">0.0844</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-Linear</td>
<td style="text-align: right;">0.1082</td>
<td style="text-align: right;">0.1068</td>
</tr>
<tr class="even">
<td style="text-align: left;">Year Interaction</td>
<td style="text-align: right;">0.0863</td>
<td style="text-align: right;">0.0811</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Comparing model fits shows that introducing non-linearity (Model 3) substantially improves the ability to explain NBA player salaries relative to simpler linear models. The quadratic RAPM model achieves the highest adjusted R² (10.68%), while splitting RAPM into offense and defense components (Model 2) provides modest gains over a basic RAPM model. Allowing the RAPM effect to vary across years (Model 4) slightly raises R² but fails to improve adjusted R², suggesting the interaction terms add complexity without significantly improving explanatory power.</p>
</section>
<section id="regression-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="regression-diagnostics">7.5 Regression Diagnostics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot diagnostics for best model</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get predicted values from best model</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>player_data<span class="sc">$</span>Predicted_Log_Salary <span class="ot">&lt;-</span> <span class="fu">predict</span>(model4, player_data)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>player_data<span class="sc">$</span>Predicted_Salary <span class="ot">&lt;-</span> <span class="fu">exp</span>(player_data<span class="sc">$</span>Predicted_Log_Salary)</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>player_data<span class="sc">$</span>Salary_Difference <span class="ot">&lt;-</span> player_data<span class="sc">$</span>Salary <span class="sc">-</span> player_data<span class="sc">$</span>Predicted_Salary</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>player_data<span class="sc">$</span>Pct_Difference <span class="ot">&lt;-</span> (player_data<span class="sc">$</span>Salary <span class="sc">-</span> player_data<span class="sc">$</span>Predicted_Salary) <span class="sc">/</span> player_data<span class="sc">$</span>Predicted_Salary <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot predicted vs actual values</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(player_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log</span>(Salary), <span class="at">y =</span> Predicted_Log_Salary)) <span class="sc">+</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">factor</span>(Year)), <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model Fit: Predicted vs Actual Log Salary"</span>,</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Points along diagonal line indicate perfect prediction"</span>,</span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Actual Log Salary"</span>, </span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted Log Salary"</span>,</span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Year"</span>) <span class="sc">+</span></span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_equal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The predicted vs.&nbsp;actual plot shows that while the model captures some of the variation in log salaries, substantial prediction error remains. The model tends to overestimate lower salaries and exhibits considerable scatter across all salary levels, reflecting the modest R² values observed. No obvious year-specific bias appears, suggesting the model’s performance is relatively consistent across seasons.</p>
</section>
</section>
<section id="analyzing-value-inefficiencies" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-value-inefficiencies">8. Analyzing Value Inefficiencies</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create value efficiency analysis</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>value_analysis <span class="ot">&lt;-</span> player_data <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Value_Category =</span> <span class="fu">case_when</span>(</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>      Pct_Difference <span class="sc">&lt;</span> <span class="sc">-</span><span class="dv">20</span> <span class="sc">~</span> <span class="st">"Underpaid"</span>,</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>      Pct_Difference <span class="sc">&gt;</span> <span class="dv">20</span> <span class="sc">~</span> <span class="st">"Overpaid"</span>,</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Fair Value"</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Count by category</span></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>value_counts <span class="ot">&lt;-</span> value_analysis <span class="sc">%&gt;%</span></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Value_Category, Year) <span class="sc">%&gt;%</span></span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Value_Category'. You can override using
the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot value distribution by year</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(value_counts, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Year), <span class="at">y =</span> Count, <span class="at">fill =</span> Value_Category)) <span class="sc">+</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Player Value Categories by Year"</span>,</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Based on difference between actual and predicted salary"</span>,</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Proportion"</span>,</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Value Category"</span>) <span class="sc">+</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 15 overpaid players (by percentage)</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>overpaid_players <span class="ot">&lt;-</span> value_analysis <span class="sc">%&gt;%</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Pct_Difference)) <span class="sc">%&gt;%</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Player, Year, LA_RAPM, Salary, Predicted_Salary, Pct_Difference) <span class="sc">%&gt;%</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">15</span>)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 15 underpaid players (by percentage)</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>underpaid_players <span class="ot">&lt;-</span> value_analysis <span class="sc">%&gt;%</span></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Pct_Difference) <span class="sc">%&gt;%</span></span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Player, Year, LA_RAPM, Salary, Predicted_Salary, Pct_Difference) <span class="sc">%&gt;%</span></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">15</span>)</span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Format tables for display</span></span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a>format_salary_table <span class="ot">&lt;-</span> <span class="cf">function</span>(df) {</span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span></span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">Salary =</span> <span class="fu">dollar</span>(Salary<span class="sc">/</span><span class="fl">1e6</span>, <span class="at">suffix =</span> <span class="st">"M"</span>),</span>
<span id="cb64-18"><a href="#cb64-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">Predicted_Salary =</span> <span class="fu">dollar</span>(Predicted_Salary<span class="sc">/</span><span class="fl">1e6</span>, <span class="at">suffix =</span> <span class="st">"M"</span>),</span>
<span id="cb64-19"><a href="#cb64-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">Pct_Difference =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(Pct_Difference, <span class="dv">1</span>), <span class="st">"%"</span>)</span>
<span id="cb64-20"><a href="#cb64-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb64-21"><a href="#cb64-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb64-22"><a href="#cb64-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-23"><a href="#cb64-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Display tables</span></span>
<span id="cb64-24"><a href="#cb64-24" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">format_salary_table</span>(overpaid_players), </span>
<span id="cb64-25"><a href="#cb64-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Top 15 Potentially Overpaid Players"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 15 Potentially Overpaid Players</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 23%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Player</th>
<th style="text-align: right;">Year</th>
<th style="text-align: right;">LA_RAPM</th>
<th style="text-align: left;">Salary</th>
<th style="text-align: left;">Predicted_Salary</th>
<th style="text-align: left;">Pct_Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Terry Rozier</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">-2.63</td>
<td style="text-align: left;">$19.89M</td>
<td style="text-align: left;">$1.15M</td>
<td style="text-align: left;">1631.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nikola Vucevic</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">-1.43</td>
<td style="text-align: left;">$26.00M</td>
<td style="text-align: left;">$1.57M</td>
<td style="text-align: left;">1554.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Andre Drummond</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">-1.34</td>
<td style="text-align: left;">$27.09M</td>
<td style="text-align: left;">$1.84M</td>
<td style="text-align: left;">1375.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kevin Love</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">-1.12</td>
<td style="text-align: left;">$28.94M</td>
<td style="text-align: left;">$1.99M</td>
<td style="text-align: left;">1354.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Andre Drummond</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">-0.92</td>
<td style="text-align: left;">$28.75M</td>
<td style="text-align: left;">$1.99M</td>
<td style="text-align: left;">1341.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gordon Hayward</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">-0.77</td>
<td style="text-align: left;">$28.50M</td>
<td style="text-align: left;">$2.14M</td>
<td style="text-align: left;">1232%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kyle Lowry</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">-0.56</td>
<td style="text-align: left;">$30.50M</td>
<td style="text-align: left;">$2.36M</td>
<td style="text-align: left;">1192%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kyrie Irving</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">-0.40</td>
<td style="text-align: left;">$31.74M</td>
<td style="text-align: left;">$2.58M</td>
<td style="text-align: left;">1127.9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stephen Curry</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: left;">$40.23M</td>
<td style="text-align: left;">$3.33M</td>
<td style="text-align: left;">1106.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kristaps Porzingis</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">-0.46</td>
<td style="text-align: left;">$29.47M</td>
<td style="text-align: left;">$2.47M</td>
<td style="text-align: left;">1091.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Russell Westbrook</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: left;">$38.51M</td>
<td style="text-align: left;">$3.29M</td>
<td style="text-align: left;">1071.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jeff Teague</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">-1.60</td>
<td style="text-align: left;">$19.00M</td>
<td style="text-align: left;">$1.67M</td>
<td style="text-align: left;">1037.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">John Wall</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: left;">$41.25M</td>
<td style="text-align: left;">$3.63M</td>
<td style="text-align: left;">1036.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">James Harden</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: left;">$41.25M</td>
<td style="text-align: left;">$3.80M</td>
<td style="text-align: left;">984.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mike Conley</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: left;">$32.51M</td>
<td style="text-align: left;">$3.01M</td>
<td style="text-align: left;">979.6%</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">format_salary_table</span>(underpaid_players), </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Top 15 Potentially Underpaid Players"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 15 Potentially Underpaid Players</caption>
<colgroup>
<col style="width: 30%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 22%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Player</th>
<th style="text-align: right;">Year</th>
<th style="text-align: right;">LA_RAPM</th>
<th style="text-align: left;">Salary</th>
<th style="text-align: left;">Predicted_Salary</th>
<th style="text-align: left;">Pct_Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Elijah Bryant</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: left;">$0.02M</td>
<td style="text-align: left;">$3.10M</td>
<td style="text-align: left;">-99.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thanasis Antetokounmpo</td>
<td style="text-align: right;">2015</td>
<td style="text-align: right;">-0.07</td>
<td style="text-align: left;">$0.03M</td>
<td style="text-align: left;">$3.47M</td>
<td style="text-align: left;">-99.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brandon Goodwin</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">-0.04</td>
<td style="text-align: left;">$0.06M</td>
<td style="text-align: left;">$3.92M</td>
<td style="text-align: left;">-98.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Louis King</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: left;">$0.05M</td>
<td style="text-align: left;">$3.26M</td>
<td style="text-align: left;">-98.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alex Caruso</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: left;">$0.08M</td>
<td style="text-align: left;">$5.11M</td>
<td style="text-align: left;">-98.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cameron Oliver</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">-0.26</td>
<td style="text-align: left;">$0.04M</td>
<td style="text-align: left;">$2.72M</td>
<td style="text-align: left;">-98.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yuta Watanabe</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: left;">$0.08M</td>
<td style="text-align: left;">$4.81M</td>
<td style="text-align: left;">-98.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Axel Toupane</td>
<td style="text-align: right;">2015</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: left;">$0.06M</td>
<td style="text-align: left;">$3.60M</td>
<td style="text-align: left;">-98.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PJ Dozier</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: left;">$0.08M</td>
<td style="text-align: left;">$4.40M</td>
<td style="text-align: left;">-98.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Duncan Robinson</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: left;">$0.08M</td>
<td style="text-align: left;">$4.38M</td>
<td style="text-align: left;">-98.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Torrey Craig</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: left;">$0.08M</td>
<td style="text-align: left;">$4.34M</td>
<td style="text-align: left;">-98.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shake Milton</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: left;">$0.08M</td>
<td style="text-align: left;">$4.21M</td>
<td style="text-align: left;">-98.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alex Caruso</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: left;">$0.08M</td>
<td style="text-align: left;">$4.18M</td>
<td style="text-align: left;">-98.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Monte Morris</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: left;">$0.08M</td>
<td style="text-align: left;">$4.14M</td>
<td style="text-align: left;">-98.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">JaKarr Sampson</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: left;">$0.08M</td>
<td style="text-align: left;">$4.09M</td>
<td style="text-align: left;">-98.1%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This visual shows us a lot of players were overpaid.</p>
</section>
<section id="discussion-findings" class="level2">
<h2 class="anchored" data-anchor-id="discussion-findings">9. Discussion &amp; Findings</h2>
<p>Based on our exploratory data analysis and regression modeling:</p>
<ol type="1">
<li><strong>RAPM as Salary Predictor</strong>:
<ul>
<li>RAPM metrics show moderate correlation with player salaries</li>
<li>The relationship is statistically significant but explains only part of salary variation</li>
<li>Hypothesis H1 is partially supported: RAPM does predict salary but with limitations</li>
</ul></li>
<li><strong>Offensive vs.&nbsp;Defensive Value</strong>:
<ul>
<li>Offensive RAPM has a stronger relationship with salary than defensive RAPM</li>
<li>This suggests teams may value offensive contributions more highly in their compensation decisions</li>
<li>Hypothesis H3 is supported: there are systematic inefficiencies in how offensive vs.&nbsp;defensive contributions are valued</li>
</ul></li>
<li><strong>Year-over-Year Analysis</strong>:
<ul>
<li>Salary growth outpaces performance changes for many players</li>
<li>Changes in performance don’t always correlate strongly with changes in compensation</li>
<li>Hypothesis H4 is supported: we observe consistent relationships between performance and salary across years</li>
</ul></li>
<li><strong>Model Performance</strong>:
<ul>
<li>Including year effects improves model performance considerably</li>
<li>The most complex model explains approximately XX% of variation in player salaries</li>
<li>Significant unexplained variation suggests other factors beyond RAPM affect compensation</li>
</ul></li>
</ol>
</section>
<section id="limitations-future-research" class="level2">
<h2 class="anchored" data-anchor-id="limitations-future-research">10. Limitations &amp; Future Research</h2>
<p><strong>Limitations of the current analysis:</strong></p>
<ol type="1">
<li><strong>Limited metrics</strong>: We focused primarily on RAPM metrics without traditional box score statistics</li>
<li><strong>Contract details</strong>: We don’t account for contract length, structure, or timing</li>
<li><strong>Market factors</strong>: Team market size, cap space, and competitive situation aren’t considered</li>
<li><strong>Player characteristics</strong>: Age, experience, injury history, and intangible contributions aren’t captured</li>
</ol>
<p><strong>Future research directions:</strong></p>
<ol type="1">
<li>Incorporate additional performance metrics beyond RAPM</li>
<li>Include contract details and salary cap information</li>
<li>Account for player experience and career trajectory</li>
<li>Consider team-level factors in salary determination</li>
<li>Develop a more comprehensive model of player value</li>
</ol>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">11. Conclusion</h2>
<p>This analysis demonstrates that NBA player salaries are related to on-court performance as measured by RAPM metrics, but the relationship is complex and influenced by various factors. Key findings suggest that:</p>
<ol type="1">
<li>RAPM metrics explain a significant portion of salary variation</li>
<li>Offensive contributions appear more highly valued than defensive contributions</li>
<li>Salary inefficiencies exist, with some players significantly over or underpaid relative to their statistical performance</li>
<li>Year-to-year trends show increasing salaries without corresponding performance increases</li>
</ol>
<p>These insights contribute to our understanding of NBA labor markets and suggest opportunities for teams to gain competitive advantages through more efficient salary allocation. Future research should focus on developing more comprehensive models of player value that incorporate additional factors beyond performance metrics.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>